spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/devww?characterEncoding=UTF-8&serverTimezone=UTC
    username: devww
    password: devww
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 80
#server log setting
logging:
  level:
    root: info