spring:
  datasource:
    #h2:
    #  console:
    #    enabled: true
    #    path: /h2-console
    #url: jdbc:h2:mem:cdri
    #username: book
    #password: book@@
    #driverClassName: org.h2.Driver
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bookdata?characterEncoding=UTF-8&serverTimezone=UTC
    username: book
    password: book@@
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
   # hibernate:
   #   ddl-auto: create
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 80
#server log setting
logging:
  level:
    org.hibernate.sql: debug